# Generated by Django 5.1.6 on 2025-04-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('FOOD_GRADE', 'Food Grade'), ('GENERAL', 'General Goods'), ('ENDANGERED', 'Endangered Goods')], max_length=20)),
                ('subcategory', models.CharField(choices=[('ELECTRONICS', 'Electronics & Accessories'), ('KITCHEN', 'Small Kitchen Appliances'), ('PERSONAL_CARE', 'Personal Care & Cosmetics'), ('APPAREL', 'Apparel & Accessories'), ('OTHER', 'Other')], max_length=20)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_fragile', models.BooleanField(default=False)),
                ('requires_refrigeration', models.BooleanField(default=False)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
