# Generated by Django 5.0.3 on 2025-05-01 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_length_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fill_capacity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PackedBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField(default=1)),
                ('fill_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_boxes', to='api.box')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_boxes', to='api.product')),
            ],
        ),
    ]
