# Generated by Django 5.1.6 on 2025-04-30 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('requires_temperature_control', models.BooleanField(default=False)),
                ('hazardous', models.BooleanField(default=False)),
                ('fragile', models.BooleanField(default=False)),
                ('special_requirements', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length_cm', models.FloatField()),
                ('width_cm', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('max_weight_kg', models.FloatField()),
                ('volume_cubic_m', models.FloatField()),
                ('temperature_controlled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FreightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FreightRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cargo_weight_kg', models.FloatField()),
                ('cargo_volume_cubic_m', models.FloatField()),
                ('additional_notes', models.TextField(blank=True)),
                ('cargo_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freight_recommender.cargocategory')),
                ('recommended_container_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freight_recommender.containertype')),
                ('recommended_freight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freight_recommender.freighttype')),
                ('recommended_load_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freight_recommender.loadtype')),
            ],
        ),
    ]
